import 'package:flutter/material.dart';
import 'package:frontend/coreFunctionality/modes/dataCollection/collectionDataP1.dart';
import 'package:frontend/coreFunctionality/modes/dataCollection/collectionDatap2.dart';
import 'package:frontend/coreFunctionality/modes/inferencing/inferencing.dart';
import 'coreFunctionality/instructionPage/collecting_data_instruction.dart';
import 'coreFunctionality/modes/dataCollection/collectionData.dart';
import 'coreFunctionality/pose_detector_view.dart';
import 'coreFunctionality/instructionPage/instructionPage.dart';
import 'coreFunctionality/instructionPage/inferencingInfoPage.dart';
import 'coreFunctionality/resultsPage/inferencingResults.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'providers.dart';
import 'package:showcaseview/showcaseview.dart';

void main() {
  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // body:inferencing(
      //   restDuration: 30,
      //   setsNeeded: 3,
      //   model:
      //       'assets/models/wholeModel/newtest23.tflite',
      //   nameOfExercise: "TESTING",
      //   numberOfExecution: 2,
      // ),
      body: collectionData(),

      // body: ShowCaseWidget(
      //   builder: Builder(builder: (context) => collectionData()),
      // ),

      // body: collectionDataP2(),
    );
  }
}




// inferencing(
//         restDuration: 30,
//         setsNeeded: 3,
//         model:
//             'assets/models/wholeModel/newtest23.tflite',
//         nameOfExercise: "TESTING",
//         numberOfExecution: 2,
//       ),


// collectionData(),

// inferencing(
//         restDuration: 30,
//         setsNeeded: 3,
//         model:
//             'assets/models/wholeModel/newtest22.tflite',
//         nameOfExercise: "TESTING",
//         numberOfExecution: 10,
//       ),




// inferencing(
//         restDuration: 30,
//         setsNeeded: 3,
//         model:
//             'assets/models/wholeModel/newtest17.tflite',
//         nameOfExercise: "TESTING",
//         numberOfExecution: 10,
//       ),


      // body: inferencing(
      //   restDuration: 30,
      //   setsNeeded: 5,
      //   model: "",
      //   nameOfExercise: "TESTING",
      //   numberOfExecution: 30,
      // ),

// inferenceInfoPage(
//         imagePreviewPath: '',
//         inferencingModelPath:
            // 'assets/models/wholeModel/MadeUpExercise1.048)(acc_0.987).tflite',
//         exerciseName: 'Exercise:',
//         exerciseNameDescription: 'Jumping Jacks',
//         numberOfExecution: 'Number of execution',
//         numberOfExecutionDescription: 2,
//         setsNeeded: 'Sets',
//         setsNeededDescription: 5,
//         restDuration: 'Rest duration',
//         restDurationDescription: 30,
//         bodyPartTarget: 'Target body paty',
//         bodyPartTargetDescription: 'Arm and Legs',
//         perspective: 'Perspective',
//         perspectiveDescription: 'Front',
//         userMade: 'Made by',
//         userMadeDescription: 'Generated by the app',
//         longDescriptionTitle: 'Description / suggestion :',
//         longDescription:
//             'You just jump and do the thingy...nothing more nothing less',
//       ),

// instructionPage(
//   isInferencing: false,
// ),

//  inferenceInfoPage(
//         imagePreviewPath: '',
//         inferencingModelPath:
//             'assets/models/wholeModel/MadeUpExercise1.048)(acc_0.987).tflite',
//         exerciseName: 'Exercise:',
//         exerciseNameDescription: 'Jumping Jacks',
//         numberOfExecution: 'Number of execution',
//         numberOfExecutionDescription: 2,
//         setsNeeded: 'Sets',
//         setsNeededDescription: 5,
//         restDuration: 'Rest duration',
//         restDurationDescription: 30,
//         bodyPartTarget: 'Target body paty',
//         bodyPartTargetDescription: 'Arm and Legs',
//         perspective: 'Perspective',
//         perspectiveDescription: 'Front',
//         userMade: 'Made by',
//         userMadeDescription: 'Generated by the app',
//         longDescriptionTitle: 'Description / suggestion :',
//         longDescription:
//             'You just jump and do the thingy...nothing more nothing less',
//       ),

// inferenceInfoPage(
//         imagePreviewPath: '',
//         inferencingModelPath:
//             'assets/models/wholeModel/firstExerciseModel(loss_0.11)(acc_0.991).tflite',
//         exerciseName: 'Exercise:',
//         exerciseNameDescription: 'Made up exercise 1',
//         numberOfExecution: 'Number of execution',
//         numberOfExecutionDescription: 2,
//         setsNeeded: 'Sets',
//         setsNeededDescription: 5,
//         restDuration: 'Rest duration',
//         restDurationDescription: 30,
//         bodyPartTarget: 'Target body paty',
//         bodyPartTargetDescription: 'Arm',
//         perspective: 'Perspective',
//         perspectiveDescription: 'Front',
//         userMade: 'Made by',
//         userMadeDescription: 'Generated by the app',
//         longDescriptionTitle: 'Description / suggestion :',
//         longDescription:
//             'Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah ',
//       ),

// inferencingReults(
//       exerciseNameDescription: "made up exercise 1",
//       numberOfExecutionDescription: 50,
//       timeDescription: 50,
//       attemptsDescription: 50,

//     )

