# Generated by Django 4.1 on 2024-04-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetInfo",
            fields=[
                ("datasetID", models.IntegerField(primary_key=True, serialize=False)),
                ("datasetURL", models.CharField(max_length=250)),
                ("numExecution", models.IntegerField()),
                ("avgSequence", models.FloatField()),
                ("minSequence", models.IntegerField()),
                ("maxSequence", models.IntegerField()),
                ("isPositive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseInfo",
            fields=[
                ("userID", models.CharField(default="696969", max_length=100)),
                ("exerciseID", models.IntegerField(primary_key=True, serialize=False)),
                ("exerciseDemo", models.CharField(max_length=100)),
                ("exerciseName", models.CharField(max_length=100)),
                ("ignoreCoordinates", models.CharField(max_length=300)),
                ("numExecution", models.IntegerField()),
                ("numSet", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                ("modelID", models.IntegerField(primary_key=True, serialize=False)),
                ("modelUrl", models.CharField(max_length=300)),
                ("valLoss", models.FloatField()),
                ("valAccuracy", models.FloatField()),
                (
                    "datasetID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelTraining.datasetinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="datasetinfo",
            name="exerciseID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="modelTraining.exerciseinfo",
            ),
        ),
    ]
