# Generated by Django 4.1 on 2024-03-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetInfo",
            fields=[
                ("datasetID", models.IntegerField(primary_key=True, serialize=False)),
                ("datasetUrl", models.CharField(max_length=100)),
                ("avgLuminance", models.FloatField()),
                ("numExecution", models.IntegerField()),
                ("avgSequence", models.IntegerField()),
                ("minSequence", models.IntegerField()),
                ("maxSequence", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                ("modelID", models.IntegerField(primary_key=True, serialize=False)),
                ("modelUrl", models.CharField(max_length=100)),
                ("valLoss", models.FloatField()),
                ("valAccuracy", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainingInfo",
            fields=[
                (
                    "userIDCreatedBy",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelTraining.datasetinfo",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelTraining.modelinfo",
                    ),
                ),
            ],
        ),
    ]
