# Generated by Django 4.1 on 2024-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelTraining", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetinfo",
            name="datasetID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="exerciseinfo",
            name="exerciseID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="modelinfo",
            name="modelID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
