# Generated by Django 4.1 on 2024-03-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modelTraining", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetinfo",
            name="avgSequence",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="ExerciseInfo",
            fields=[
                ("exerciseID", models.IntegerField(primary_key=True, serialize=False)),
                ("exerciseName", models.CharField(max_length=100)),
                ("partAffected", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=150)),
                ("additionalNotes", models.CharField(max_length=150)),
                ("numExecution", models.IntegerField()),
                ("numSet", models.IntegerField()),
                (
                    "modelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelTraining.modelinfo",
                    ),
                ),
            ],
        ),
    ]
