# Generated by Django 4.1 on 2024-03-31 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modelTraining", "0002_alter_datasetinfo_avgsequence_exerciseinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traininginfo",
            old_name="userIDCreatedBy",
            new_name="trainingInstanceKey",
        ),
        migrations.AlterField(
            model_name="modelinfo",
            name="modelUrl",
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name="UserTrainingInfo",
            fields=[
                ("userId", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "trainingInstanceKey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modelTraining.traininginfo",
                    ),
                ),
            ],
        ),
    ]
