# Generated by Django 4.1 on 2024-03-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "modelTraining",
            "0003_rename_useridcreatedby_traininginfo_traininginstancekey_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciseinfo",
            name="additionalNotes",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="exerciseinfo",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
